name: Deploy ASP.NET Core app to Azure Web App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x' # Adjust this to the .NET version you're using

    - name: Install dependencies
      run: dotnet restore back-end/back-end.csproj # Adjust the path to your .csproj or .sln file

    - name: Build
      run: dotnet build back-end/back-end.csproj --configuration Release --no-restore # Adjust the path to your .csproj or .sln file

    - name: Publish
      run: dotnet publish back-end/back-end.csproj -c Release -o ${{ github.workspace }}/publish --no-build # Adjust the path to your .csproj or .sln file

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'your-app-service-name' # Replace with your App Service name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ github.workspace }}/publish
        
    - name: Run EF Core migrations
      run: dotnet ef database update --project back-end/back-end.csproj
